on:
  workflow_call:
    inputs:
      CONFIGURATION:
        type: string
        default: Release
      VERSION:
        type: string
        default: 0.0.0
      UPLOAD_ARTIFACTS:
        type: boolean
        default: false
jobs:

  build:
    name: Build

    strategy:
      matrix:
        include:
        - platform: x64
          runner: windows-latest
        - platform: arm64
          runner: windows-11-arm

    runs-on: ${{ matrix.runner }}

    steps:

    - name: Checkout
      uses: actions/checkout@v7

    - name: Setup .NET
      uses: actions/setup-dotnet@v6
      with:
        dotnet-version: 10.0.x

    - name: Build
      run: dotnet publish ./src/XboxModeCli/ -r $env:RUNTIME_ID -c $env:CONFIGURATION -o $env:OUTPUT_DIR -p:Version=$env:VERSION
      env:
        CONFIGURATION: ${{ inputs.CONFIGURATION }}
        RUNTIME_ID: win-${{ matrix.platform }}
        OUTPUT_DIR: ${{ github.workspace }}/Publish/${{ matrix.platform }}
        VERSION: ${{ inputs.VERSION }}

    - name: Stage Artifacts
      shell: pwsh
      run: |
        $destinationDir = Split-Path $env:DESTINATION
        New-Item -ItemType Directory -Path $destinationDir -Force | Out-Null
        Compress-Archive -Path $env:SOURCE -DestinationPath $env:DESTINATION -Force
      env:
        SOURCE: ${{ github.workspace }}/Publish/${{ matrix.platform }}/*.exe
        DESTINATION: ${{ github.workspace }}/ArtifactStaging/XboxModeCli_${{ matrix.platform }}_${{ github.ref_name }}.zip
      if: ${{ inputs.UPLOAD_ARTIFACTS == true }}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v7
      with:
        name: XboxModeCli_${{ matrix.platform }}_${{ github.ref_name }}
        path: |
          ${{ github.workspace }}/ArtifactStaging/XboxModeCli_${{ matrix.platform }}_${{ github.ref_name }}.zip
      if: ${{ inputs.UPLOAD_ARTIFACTS == true }}
