on:
  workflow_call:
    inputs:
      IS_PRERELEASE:
        type: boolean
        default: false
      PREVIOUS_TAG:
        type: string

jobs:

  publish:
    name: GitHub Releases Publish

    runs-on: ubuntu-latest

    steps:
      - name: Download Release Artifacts
        uses: actions/download-artifact@v8
        with:
          pattern: 'XboxModeCli_*'
          merge-multiple: true

      - name: Create Release
        uses: softprops/action-gh-release@v3
        with:
          files: '**/XboxModeCli_*.zip'
          draft: true
          prerelease: ${{ inputs.IS_PRERELEASE }}
          generate_release_notes: true
          previous_tag: ${{ inputs.PREVIOUS_TAG }}
